server:
  port: 9091 # 랜덤포트

spring:
  application:
    name: api-client-A # 서비스 이름

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:9091}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka