spring:
  data:
    redis:
      port: 6379
      host: localhost
      ssl:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lock
    username: admin
    password: testPassword@
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: VARCHAR
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
      org:
        springframework: DEBUG
        hibernate:
          orm:
            jdbc:
              bind: trace