server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    member:
      url: jdbc:postgresql://localhost:5432/member
      username: postgres
      password: postgres
      hikari:
        maximum-pool-size: 24
        minimum-idle: 5
      driver-class-name: org.postgresql.Driver

    team:
      url: jdbc:postgresql://localhost:5432/team
      username: postgres
      password: postgres
      hikari:
          maximum-pool-size: 24
          minimum-idle: 5
      driver-class-name: org.postgresql.Driver

logging:
  level:
    com:
      message: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
      hibernate:
        orm:
          jdbc:
            bind: trace

